### ISSUE TITLE
how do I turn unicode to normal strings?

### ISSUE THREAD

**Issue by HERRKIN** [emilsedgh/pdu#6]
if I send 'mañana josé'
I have this in msg.text

text: 'Ma}ana Jos\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000' 

I dont know how to deal with it so I can see the text without the scapes.

**Comment by emilsedgh** [comment]
It seems that some sms centers fill all the empty space in a message using "\u0000".
So they are actually present when modem receives them.
just remove them from your message using String.replace

**Comment by HERRKIN** [comment]
what about this? Ma}ana Jos\u000 how do I make it say Mañana josé???

**Comment by emilsedgh** [comment]
It is kind of weird, could you please send me the PDU?
I used this module to send a lot of non-ascii messages and never had such problem.
